### ISSUE TITLE
Not a valid version

### ISSUE THREAD

**Issue by gjedeer** [pypa/distlib#173]
Distlib cannot resolve a version specification that pip resolves without any issues.

How to reproduce:

```
 docker run -it --rm python:3.9 /bin/bash
root@4171c15d98ef:/# pip install distlib
Collecting distlib
  Downloading distlib-0.3.4-py2.py3-none-any.whl (461 kB)
     |████████████████████████████████| 461 kB 80 kB/s 
Installing collected packages: distlib
Successfully installed distlib-0.3.4
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
WARNING: You are using pip version 21.2.4; however, version 22.1.2 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
root@4171c15d98ef:/# python
Python 3.9.7 (default, Sep 28 2021, 18:32:58) 
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import distlib.locators
>>> distlib.locators.SimpleScrapingLocator('https://pypi.python.org/simple/').locate('protobuf (<4.0.0dev,>=3.15.0)')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/distlib/locators.py", line 369, in locate
    self.matcher = matcher = scheme.matcher(r.requirement)
  File "/usr/local/lib/python3.9/site-packages/distlib/version.py", line 125, in __init__
    vn, prefix = self.version_class(s), False
  File "/usr/local/lib/python3.9/site-packages/distlib/version.py", line 33, in __init__
    self._parts = parts = self.parse(s)
  File "/usr/local/lib/python3.9/site-packages/distlib/version.py", line 267, in parse
    result = _normalized_key(s)
  File "/usr/local/lib/python3.9/site-packages/distlib/version.py", line 188, in _pep_440_key
    raise UnsupportedVersionError('Not a valid version: %s' % s)
distlib.version.UnsupportedVersionError: Not a valid version: 4.0.0dev
```

How pip does it:
```
root@26196ad573b2:/# pip install 'protobuf (<4.0.0dev,>=3.15.0)'
Collecting protobuf<4.0.0dev,>=3.15.0
  Downloading protobuf-3.20.1-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.whl (1.0 MB)
     |████████████████████████████████| 1.0 MB 666 kB/s 
Installing collected packages: protobuf
Successfully installed protobuf-3.20.1

```

**Comment by vsajip** [comment]
That's because the version number `4.0.0dev` is a _legacy_ version number, not conforming to PEP440. To work with these legacy numbers, specify `scheme='legacy'` in the locator initializer:

```
~/projects/distlib [default] $ python3
Python 3.12.0a0 (heads/main:324d01944d, Jul  5 2022, 15:09:14) [GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import distlib.locators
>>> distlib.locators.SimpleScrapingLocator('https://pypi.python.org/simple/', scheme='legacy').locate('protobuf (<4.0.0dev,>=3.15.0)')
<Distribution protobuf (3.20.1) [https://files.pythonhosted.org/packages/ef/c8/2e7f7feaf804b7206e6cc8fa3f0f49834a78f7cb127813d2c45e42d5f7bf/protobuf-3.20.1-py2.py3-none-any.whl]>
>>> 
```

**Comment by gjedeer** [comment]
Thank you!
